# Copyright (C) 2020, 2023 Mitsubishi Electric Research Laboratories (MERL)
#
# SPDX-License-Identifier: AGPL-3.0-or-later
"""
Gym environment wrapper for MC-PILCO
"""

import numpy as np


class Gym_Model:
    """
    Standard Gym environment wrapper for MC-PILCO
    """

    def __init__(self, env):
        """
        env: gym environment instance (already created)
        """
        self.env = env

    def rollout(self, s0, policy, T, dt, noise, road_profile=None, reset_kwargs=None, collect_road=False):
        """
        Generate a rollout of length T (s) for the gym environment with
        control inputs computed by 'policy' and applied with a sampling time 'dt'.
        'noise' defines the standard deviation of a Gaussian measurement noise.
            s0: initial state
            policy: policy function
            T: length rollout (s)
            dt: sampling time (s)
            noise: measurement noise std
            road_profile: optional road profile (for compatibility, may not be used by all envs)
            reset_kwargs: optional keyword arguments forwarded to env.reset
            collect_road: if True, also return [z_r, z_r_dot] sampled from env info
        """
        state_dim = len(s0)
        times = np.linspace(0, T, int(T / dt) + 1)

        # Reset environment with initial state and optional deterministic reset parameters.
        reset_call_kwargs = dict(reset_kwargs or {})
        reset_args = getattr(self.env.reset, "__code__", None)
        if reset_args is not None and "init_state" in reset_args.co_varnames:
            reset_call_kwargs.setdefault("init_state", s0)

        try:
            reset_result = self.env.reset(**reset_call_kwargs)
        except TypeError:
            if reset_args is not None and "init_state" in reset_args.co_varnames:
                reset_result = self.env.reset(init_state=s0)
            else:
                reset_result = self.env.reset()

        # Handle both old gym API (returns obs) and new gymnasium API (returns obs, info)
        if isinstance(reset_result, tuple):
            obs = reset_result[0]
        else:
            obs = reset_result

        states = obs.reshape(1, -1)
        noisy_states = states + np.random.randn(state_dim) * noise
        road_samples = []

        if collect_road:
            road_samples.append(self._get_road_position_from_env())

        # Get initial input
        inputs = np.array([policy(noisy_states[0, :], 0)]).reshape(1, -1)

        # Rollout
        for k in range(1, len(times)):
            # Apply input
            step_result = self.env.step(inputs[k - 1, :])

            # Handle step return: (obs, reward, done, info) or (obs, reward, terminated, truncated, info)
            new_obs = step_result[0]
            info_dict = step_result[-1] if len(step_result) > 0 else {}

            noisy_new_obs = new_obs + np.random.randn(state_dim) * noise

            # Append new state
            states = np.append(states, [new_obs], axis=0)
            noisy_states = np.append(noisy_states, [noisy_new_obs], axis=0)
            if collect_road:
                road_samples.append(self._get_road_position_from_info(info_dict))

            # Compute next input
            u_next = np.array([policy(noisy_states[k, :], times[k])]).reshape(1, -1)
            inputs = np.append(inputs, u_next, axis=0)

        if collect_road:
            road_samples = np.asarray(road_samples, dtype=float).reshape(-1)
            if road_samples.size != states.shape[0]:
                road_samples = np.resize(road_samples, states.shape[0])
            road_dt = self._get_road_sample_time(dt)
            road_speed = np.gradient(road_samples, road_dt) if road_samples.size > 1 else np.zeros_like(road_samples)
            return noisy_states, inputs, states, np.column_stack([road_samples, road_speed])

        return noisy_states, inputs, states

    def _get_road_position_from_info(self, info_dict):
        """
        GOPS quarter-car env exposes physical signals in info["info"].
        Index 5 is the road displacement generated by the Simulink model.
        """
        try:
            info_arr = info_dict.get("info", None)
        except AttributeError:
            info_arr = None
        if info_arr is not None:
            try:
                return float(np.asarray(info_arr).reshape(-1)[5])
            except (IndexError, TypeError, ValueError):
                pass
        return self._get_road_position_from_env()

    def _get_road_position_from_env(self):
        try:
            info_arr = self.env.env.model_class.quarter_sus_imp_force_Y.info
            return float(np.asarray(info_arr).reshape(-1)[5])
        except (AttributeError, IndexError, TypeError, ValueError):
            return 0.0

    def _get_road_sample_time(self, default_dt):
        env_dt = float(getattr(self.env, "dt", default_dt))
        act_repeat = int(getattr(self.env, "act_repeat", 1))
        return env_dt * max(act_repeat, 1)
